# -*- coding: utf-8 -*-
"""UK_Accident_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184j_H_j1fPaFaqZODEcH_-3b7j6Hb2xB
"""

from google.colab import files
uploaded = files.upload()

!pip install pyproj folium

import pandas as pd

df = pd.read_csv("dataset.csv")

df.info()
df.head()

from pyproj import Transformer

transformer = Transformer.from_crs("epsg:27700", "epsg:4326", always_xy=True)

# Apply conversion for lattitude and longitude
df["Longitude"], df["Latitude"] = transformer.transform(
    df["Grid Ref: Easting"].values,
    df["Grid Ref: Northing"].values
)

df[["Grid Ref: Easting", "Grid Ref: Northing", "Longitude", "Latitude"]].head()

# Heat Map
import folium
from folium.plugins import HeatMap
import IPython.display as ipd
from IPython.display import display

df_map = df.dropna(subset=["Latitude", "Longitude"])
sample_size = min(1000, len(df_map))
heat_data = df_map[["Latitude", "Longitude"]].sample(sample_size).values.tolist()

m = folium.Map(location=[54, -2], zoom_start=6)
HeatMap(heat_data).add_to(m)
m.save("uk_accident_heatmap.html")

# Display map
#display(ipd.HTML(filename="uk_accident_heatmap.html"))


# Download
files.download("uk_accident_heatmap.html")

# Filter only high severity
df_severe = df_map[df_map["Casualty Severity"] <= 2]

heat_data_severe = df_severe[["Latitude", "Longitude"]].sample(min(1000, len(df_severe))).values.tolist()

# Create new map
m_severe = folium.Map(location=[54, -2], zoom_start=6)
HeatMap(heat_data_severe).add_to(m_severe)
m_severe.save("severe_accidents_heatmap.html")

# Download
files.download("severe_accidents_heatmap.html")

# Filter by time range
df_evening = df_map[(df_map["Time (24hr)"] >= 1600) & (df_map["Time (24hr)"] <= 2000)]

heat_data_evening = df_evening[["Latitude", "Longitude"]].sample(min(1000, len(df_evening))).values.tolist()

# Map for evening accidents
m_evening = folium.Map(location=[54, -2], zoom_start=6)
HeatMap(heat_data_evening).add_to(m_evening)
m_evening.save("evening_accidents_heatmap.html")
files.download("evening_accidents_heatmap.html")